"""empty message

Revision ID: 64f8daedbf38
Revises: 19b79cb32a7d
Create Date: 2024-05-08 10:12:36.661934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64f8daedbf38'
down_revision = '19b79cb32a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_date', sa.DateTime(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('birthdate', sa.DateTime(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('X6_birth_weight', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('diagnosis_date', sa.DateTime(), nullable=False),
    sa.Column('surgery_type', sa.String(), nullable=False),
    sa.Column('surgery_date', sa.DateTime(), nullable=False),
    sa.Column('max_weight_before_surgery', sa.Float(), nullable=False),
    sa.Column('weight_before_surgery', sa.Float(), nullable=False),
    sa.Column('min_weight_after_surgery', sa.Float(), nullable=False),
    sa.Column('therapy_before_surgery', sa.String(), nullable=False),
    sa.Column('X9_HbA1c_before_surgery', sa.Float(), nullable=False),
    sa.Column('X1_age_at_surgery', sa.Float(), nullable=False),
    sa.Column('X2_period_after_surgery', sa.Float(), nullable=False),
    sa.Column('X3_max_BMI_before_surgery', sa.Float(), nullable=False),
    sa.Column('X4_BMI_before_surgery', sa.Float(), nullable=False),
    sa.Column('X5_BMI_at_survey', sa.Float(), nullable=False),
    sa.Column('X7_min_BMI_after_surgery', sa.Float(), nullable=False),
    sa.Column('X8_illness_duration', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patients')
    # ### end Alembic commands ###
