"""empty message

Revision ID: e63c1b6c37b5
Revises: 
Create Date: 2024-05-11 23:50:36.101315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e63c1b6c37b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('pat_uuid', sa.String(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('birthdate', sa.DateTime(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('X6_birth_weight', sa.Float(), nullable=False),
    sa.Column('diagnosis_date', sa.DateTime(), nullable=False),
    sa.Column('surgery_type', sa.String(), nullable=False),
    sa.Column('surgery_date', sa.DateTime(), nullable=False),
    sa.Column('max_weight_before_surgery', sa.Float(), nullable=False),
    sa.Column('weight_before_surgery', sa.Float(), nullable=False),
    sa.Column('therapy_before_surgery', sa.String(), nullable=False),
    sa.Column('X9_HbA1c_before_surgery', sa.Float(), nullable=False),
    sa.Column('arterial_hypertension_degree', sa.String(), nullable=False),
    sa.Column('dyslipidemia', sa.String(), nullable=False),
    sa.Column('heredity', sa.String(), nullable=False),
    sa.Column('complications_history', sa.String(), nullable=False),
    sa.Column('gestational_diabetes', sa.String(), nullable=False),
    sa.Column('X1_age_at_surgery', sa.Float(), nullable=False),
    sa.Column('X3_max_BMI_before_surgery', sa.Float(), nullable=False),
    sa.Column('X4_BMI_before_surgery', sa.Float(), nullable=False),
    sa.Column('X8_illness_duration', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('fullname', 'birthdate', 'gender', 'X6_birth_weight', 'diagnosis_date', 'surgery_type')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_two_factor_authentication_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_two_factor_authenticated', sa.Boolean(), nullable=False),
    sa.Column('secret_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('secret_token'),
    sa.UniqueConstraint('username')
    )
    op.create_table('surveys',
    sa.Column('UUID', sa.String(), nullable=False),
    sa.Column('survey_date', sa.DateTime(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('min_weight_after_surgery', sa.Float(), nullable=False),
    sa.Column('X2_period_after_surgery', sa.Float(), nullable=False),
    sa.Column('X5_BMI_at_survey', sa.Float(), nullable=False),
    sa.Column('X7_min_BMI_after_surgery', sa.Float(), nullable=False),
    sa.Column('Target_HbA1c_now', sa.Float(), nullable=False),
    sa.Column('HbA1c_predicted', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['UUID'], ['patients.pat_uuid'], ),
    sa.PrimaryKeyConstraint('UUID', 'survey_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surveys')
    op.drop_table('users')
    op.drop_table('patients')
    # ### end Alembic commands ###
